import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {transformMinitoolCss} from './transform-css.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');process.chdir(root);
execFileSync(process.execPath,['node_modules/typescript/bin/tsc','-b'],{stdio:'inherit'});
execFileSync(process.execPath,['node_modules/vite/bin/vite.js','build','--config','minitool/vite.config.ts'],{stdio:'inherit'});
fs.mkdirSync('dist-minitool/assets',{recursive:true});
for(const file of ['card-back.svg','card-face.svg']) fs.copyFileSync(`public/assets/${file}`,`dist-minitool/assets/${file}`);
fs.copyFileSync('minitool/icon.png','dist-minitool/assets/icon.png');
fs.copyFileSync('minitool/compat.js','dist-minitool/compat.js');
const notices=fs.readdirSync('public/licenses').sort().map(file=>`\n${file}\n${fs.readFileSync(`public/licenses/${file}`,'utf8')}`).join('\n');
fs.writeFileSync('dist-minitool/notices.js','/*!\n'+notices.replaceAll('*/','* /')+'\n*/\n');
fs.writeFileSync('dist-minitool/index.html','<!DOCTYPE html>\n<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"><title>今天适合上班吗？</title><link rel="icon" type="image/png" href="./assets/icon.png"><link rel="stylesheet" href="./style.css"></head><body><div id="root"></div><script src="./compat.js"></script><script src="./app.js"></script></body></html>\n');
await transformMinitoolCss('dist-minitool/style.css');
execFileSync(process.execPath,['minitool/validate.mjs'],{stdio:'inherit'});
execFileSync(process.execPath,['minitool/validate-css.mjs'],{stdio:'inherit'});
execFileSync(process.execPath,['minitool/test-runtime.mjs'],{stdio:'inherit'});
